
services:
    hardhat-node:
        restart: unless-stopped
        command: >
            sh -c '
                rm -rf /usr/blockchain/ignition/deployments/* &&
                npx hardhat clean && npx hardhat compile &&
                if [ -n "$$RUN_TESTS" ] && [ "$$RUN_TESTS" = "true" ]; then
                    npm run lint && npx hardhat test --coverage && 
                    slither ./contracts --solc-remaps "@openzeppelin/=node_modules/@openzeppelin/" --solc-args "--allow-paths ." --filter-paths "node_modules" --json report.json;
                fi &&
                (while ! nc -z 172.20.0.11 8545; do sleep 1; done &&
                cp -r /usr/blockchain/artifacts/* /usr/blockchain/output/artifacts &&
                npx hardhat run scripts/deploy.ts --network besu_prod) & 
                npx hardhat node --hostname 0.0.0.0 --chain-id $$NETWORK_ID
            '
        networks:
            internal-network:
                ipv4_address: 172.20.0.11

    app:
        depends_on:
            - hardhat-node

