
FROM node:26.4-alpine3.23
WORKDIR /usr/blockchain
COPY blockchain/*.json blockchain/*.ts .
RUN npm install
RUN apk add netcat-openbsd
COPY blockchain/types/ ./types/
COPY blockchain/ignition/modules ./ignition/modules/
COPY blockchain/contracts/ ./contracts/

