from enum import Enum


class ErrorCode(str, Enum):

    USER_NOT_FOUND = "USER_NOT_FOUND"

    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"

    PASSWORD_TOO_LONG = "PASSWORD_TOO_LONG"

    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"