from enum import Enum


class ErrorCode(str, Enum):

    USER_NOT_FOUND = "USER_NOT_FOUND"

    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"

    PASSWORD_TOO_LONG = "PASSWORD_TOO_LONG"

    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"

    INVALID_CREDENTIAL = "INVALID_CREDENTIAL"

    NOT_ACTIVE_USER = "NOT_ACTIVE_USER"

    USER_IS_ACTIVE = "USER_IS_ACTIVE"

    INVALID_DOCTOR_ID = "INVALID_DOCTOR_ID"

    INVALID_DATE = "INVALID_DATE"

    USER_NOT_AUTHORIZED = "USER_NOT_AUTHORIZED"

    MISSING_VISIT_DETAILS = "MISSING_VISIT_DETAILS"

    INVALID_ROLE = "INVALID_ROLE"