from enum import Enum


class ErrorCode(str, Enum):

    USER_NOT_FOUND = "USER_NOT_FOUND"

    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"

    PASSWORD_TOO_LONG = "PASSWORD_TOO_LONG"

    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"

    INVALID_CREDENTIAL = "INVALID_CREDENTIAL"

    NOT_ACTIVE_USER = "NOT_ACTIVE_USER"

    USER_IS_ACTIVE = "USER_IS_ACTIVE"

    INVALID_DOCTOR_ID = "INVALID_DOCTOR_ID"

    INVALID_DATE = "INVALID_DATE"

    USER_NOT_AUTHORIZED = "USER_NOT_AUTHORIZED"

    MISSING_VISIT_DETAILS = "MISSING_VISIT_DETAILS"

    INVALID_ROLE = "INVALID_ROLE"

    PROBABILITY_NOT_FOUND = "PROBABILITY_NOT_FOUND"

    INVALID_PROBABILITY = "INVALID_PROBABILITY"

    TRANSACTION_FAILED = "TRANSACTION_FAILED"

    FUNCTION_NOT_FOUND = "FUNCTION_NOT_FOUND"

    EVIDENCE_ALREADY_ADDED = "EVIDENCE_ALREADY_ADDED"

    VISIT_ALREADY_CONFIRMED = "VISIT_ALREADY_CONFIRMED"

    VISIT_NOT_FOUND = "VISIT_NOT_FOUND"

    VISIT_ALREADY_OCCURRED = "VISIT_ALREADY_OCCURRED"

    VISIT_TIME_CONFLICT = "VISIT_TIME_CONFLICT"

    REQUEST_LIMIT_EXCEEDED = "REQUEST_LIMIT_EXCEEDED"

